# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: citiesGame.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='citiesGame.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63itiesGame.proto\"\x14\n\x04\x43ity\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"/\n\x08UserGame\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tcity_word\x18\x02 \x01(\t\"/\n\nGameStatus\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08game_end\x18\x02 \x01(\x08\"0\n\x08GameDone\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0b\x64one_status\x18\x02 \x01(\x08\"\x1c\n\x08UserName\x12\x10\n\x08username\x18\x01 \x01(\t\"#\n\tUserReply\x12\x16\n\x0egreeting_reply\x18\x01 \x01(\t2\xa3\x01\n\x11\x43itiesGameService\x12\"\n\x07Greeter\x12\t.UserName\x1a\n.UserReply\"\x00\x12$\n\nLobbyReady\x12\t.UserName\x1a\t.GameDone\"\x00\x12$\n\x08GameBody\x12\t.UserGame\x1a\x0b.GameStatus\"\x00\x12\x1e\n\x08\x43ityName\x12\t.UserName\x1a\x05.City\"\x00\x62\x06proto3'
)




_CITY = _descriptor.Descriptor(
  name='City',
  full_name='City',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='City.city', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=40,
)


_USERGAME = _descriptor.Descriptor(
  name='UserGame',
  full_name='UserGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='UserGame.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='city_word', full_name='UserGame.city_word', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=89,
)


_GAMESTATUS = _descriptor.Descriptor(
  name='GameStatus',
  full_name='GameStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='GameStatus.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_end', full_name='GameStatus.game_end', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=138,
)


_GAMEDONE = _descriptor.Descriptor(
  name='GameDone',
  full_name='GameDone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='GameDone.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='done_status', full_name='GameDone.done_status', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=188,
)


_USERNAME = _descriptor.Descriptor(
  name='UserName',
  full_name='UserName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='UserName.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=218,
)


_USERREPLY = _descriptor.Descriptor(
  name='UserReply',
  full_name='UserReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting_reply', full_name='UserReply.greeting_reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=255,
)

DESCRIPTOR.message_types_by_name['City'] = _CITY
DESCRIPTOR.message_types_by_name['UserGame'] = _USERGAME
DESCRIPTOR.message_types_by_name['GameStatus'] = _GAMESTATUS
DESCRIPTOR.message_types_by_name['GameDone'] = _GAMEDONE
DESCRIPTOR.message_types_by_name['UserName'] = _USERNAME
DESCRIPTOR.message_types_by_name['UserReply'] = _USERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

City = _reflection.GeneratedProtocolMessageType('City', (_message.Message,), {
  'DESCRIPTOR' : _CITY,
  '__module__' : 'citiesGame_pb2'
  # @@protoc_insertion_point(class_scope:City)
  })
_sym_db.RegisterMessage(City)

UserGame = _reflection.GeneratedProtocolMessageType('UserGame', (_message.Message,), {
  'DESCRIPTOR' : _USERGAME,
  '__module__' : 'citiesGame_pb2'
  # @@protoc_insertion_point(class_scope:UserGame)
  })
_sym_db.RegisterMessage(UserGame)

GameStatus = _reflection.GeneratedProtocolMessageType('GameStatus', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATUS,
  '__module__' : 'citiesGame_pb2'
  # @@protoc_insertion_point(class_scope:GameStatus)
  })
_sym_db.RegisterMessage(GameStatus)

GameDone = _reflection.GeneratedProtocolMessageType('GameDone', (_message.Message,), {
  'DESCRIPTOR' : _GAMEDONE,
  '__module__' : 'citiesGame_pb2'
  # @@protoc_insertion_point(class_scope:GameDone)
  })
_sym_db.RegisterMessage(GameDone)

UserName = _reflection.GeneratedProtocolMessageType('UserName', (_message.Message,), {
  'DESCRIPTOR' : _USERNAME,
  '__module__' : 'citiesGame_pb2'
  # @@protoc_insertion_point(class_scope:UserName)
  })
_sym_db.RegisterMessage(UserName)

UserReply = _reflection.GeneratedProtocolMessageType('UserReply', (_message.Message,), {
  'DESCRIPTOR' : _USERREPLY,
  '__module__' : 'citiesGame_pb2'
  # @@protoc_insertion_point(class_scope:UserReply)
  })
_sym_db.RegisterMessage(UserReply)



_CITIESGAMESERVICE = _descriptor.ServiceDescriptor(
  name='CitiesGameService',
  full_name='CitiesGameService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=258,
  serialized_end=421,
  methods=[
  _descriptor.MethodDescriptor(
    name='Greeter',
    full_name='CitiesGameService.Greeter',
    index=0,
    containing_service=None,
    input_type=_USERNAME,
    output_type=_USERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LobbyReady',
    full_name='CitiesGameService.LobbyReady',
    index=1,
    containing_service=None,
    input_type=_USERNAME,
    output_type=_GAMEDONE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GameBody',
    full_name='CitiesGameService.GameBody',
    index=2,
    containing_service=None,
    input_type=_USERGAME,
    output_type=_GAMESTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CityName',
    full_name='CitiesGameService.CityName',
    index=3,
    containing_service=None,
    input_type=_USERNAME,
    output_type=_CITY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CITIESGAMESERVICE)

DESCRIPTOR.services_by_name['CitiesGameService'] = _CITIESGAMESERVICE

# @@protoc_insertion_point(module_scope)
